name: "alpo"
configuration:
  type: alpo
  model: fat
#controller  ???
records:
  joint_states: true
  controller/odom: true
  controller/odometry: true
  controller/kinematic: true
simulation:
  initial_xyz: [0.0, 0.0, 0.0]
  initial_rpy: [0.0, 0.0, 0.0]
