remote_controller:
  type: joystick
  available_mode: simulation
embedded_controller:
  type: joystick
  available_mode: live
lms151:
  type: lidar
  available_mode: all
ublox:
  type: gps
  available_mode: all
xsens:
  type: imu
  available_mode: all
