remote_controller:
  type: joystick
  available: true
embedded_controller:
  type: joystick
  available: false
lms151:
  type: lidar
  available: true  
ublox:
  type: gps
  available: true  
xsens:
  type: imu
  available: true  